services:
  studio-api:
    container_name: studio-api
    restart: on-failure
    build: .
    environment:
      - NODE_ENV=development
    ports:
      - 3002:3002
    volumes:
      - ./src:/app/src
      - ./test:/app/test
    env_file:
      - .env
    networks:
      - calculus-network

networks:
  calculus-network:
    driver: bridge